gui:
  windowSize: 'half'
customCommands:
  - key: 'c'
    context: 'files'
    subprocess: true
    prompts:
      - type: 'menu'
        title: 'Choose your commit type:'
        key: 'CommitType'
        options:
          - name: 'âœ¨ FEATURE'
            value: 'âœ¨'
          - name: 'ğŸ› BUG'
            value: 'ğŸ›'
          - name: 'ğŸš‘ï¸ HOTFIX'
            value: 'ğŸš‘ï¸'
          - name: 'ğŸ¨ CHANGED'
            value: 'ğŸ¨'
          - name: 'ğŸ”’ï¸ SECURITY'
            value: 'ğŸ”’ï¸'
          - name: 'â¬†ï¸ BUMPED'
            value: 'â¬†ï¸'
          - name: 'ğŸš§ WIP'
            value: 'ğŸš§'
          - name: 'ğŸ”¥ REMOVED'
            value: 'ğŸ”¥'
          - name: 'ğŸ‰ INITIAL'
            value: 'ğŸ‰'
      - type: 'input'
        title: 'Enter your commit ID'
        key: 'CommitId'
        initialValue: '-'
      - type: 'input'
        title: 'Enter your commit message'
        key: 'CommitMessage'
        initialValue: ''
      - type: 'menu'
        title: 'Pre commit msg hook?'
        key: 'PreCommitHook'
        options:
          - name: 'Yes'
            value: ''
          - name: 'No'
            value: '--no-verify'
    command: "git commit -m '{{.Form.CommitType}} [{{.Form.CommitId}}] {{.Form.CommitMessage}}' {{.Form.PreCommitHook}}"
    loadingText: 'Commiting...'
  - key: 'n'
    context: 'localBranches'
    subprocess: true
    prompts:
      - type: 'menu'
        title: 'Choose your branch type:'
        key: 'BranchType'
        options:
          - name: 'âœ¨ FEATURE'
            value: 'feature'
          - name: 'ğŸ› BUG'
            value: 'bugFix'
          - name: 'ğŸš‘ï¸ HOTFIX'
            value: 'hotFix'
      - type: 'input'
        title: 'Enter your task ID'
        key: 'TaskId'
        initialValue: ''
      - type: 'input'
        title: 'Enter your branch name'
        key: 'BranchName'
        initialValue: ''
    command: "git checkout -b {{.Form.BranchType}}/T{{.Form.TaskId}}-{{.Form.BranchName}}"
    loadingText: 'Creating new branch...'
  - key: '<c-p>'
    context: 'global'
    subprocess: true
    prompts:
      - type: 'input'
        title: 'Choose your target branch'
        key: 'Target'
        suggestions:
          preset: 'branches'
        initialValue: 'develop'
    command: "~/dotfiles/lazygit/merge_request.sh {{.Form.Target}}"
    loadingText: 'Creating merge request...'
