customCommands:
  - key: 'c'
    context: 'files'
    subprocess: true
    prompts:
      - type: 'menu'
        title: 'Choose your commit type:'
        key: 'CommitType'
        options:
          - name: 'âœ¨ FEATURE'
            value: 'âœ¨'
          - name: 'ğŸ› BUG'
            value: 'ğŸ›'
          - name: 'ğŸš‘ï¸ HOTFIX'
            value: 'ğŸš‘ï¸'
          - name: 'ğŸ¨ CHANGED'
            value: 'ğŸ¨'
          - name: 'ğŸ”’ï¸ SECURITY'
            value: 'ğŸ”’ï¸'
          - name: 'â¬†ï¸ BUMPED'
            value: 'â¬†ï¸'
          - name: 'ğŸš§ WIP'
            value: 'ğŸš§'
          - name: 'ğŸ”¥ REMOVED'
            value: 'ğŸ”¥'
      - type: 'input'
        title: 'Enter your commit ID'
        key: 'CommitId'
        initialValue: '-'
      - type: 'input'
        title: 'Enter your commit message'
        key: 'CommitMessage'
        initialValue: ''
    command: "git commit -m '{{.Form.CommitType}} [{{.Form.CommitId}}] {{.Form.CommitMessage}}'"
    loadingText: 'Commiting...'
